name: general_python3
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39h5eee18b_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=6.2.0=py39h06a4308_0
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.2.25=h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_1
  - comm=0.2.2=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - h11=0.14.0=py39h06a4308_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - ipykernel=6.29.5=py39h06a4308_1
  - ipywidgets=8.1.5=py39h06a4308_0
  - jedi=0.19.2=py39h06a4308_0
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonschema=4.23.0=py39h06a4308_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter-resource-usage=1.1.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=py39h06a4308_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - jupyter_events=0.12.0=py39h06a4308_0
  - jupyter_server=2.15.0=py39h06a4308_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=py39h06a4308_0
  - jupyterlab_server=2.27.3=py39h06a4308_0
  - jupyterlab_widgets=3.0.13=py39h06a4308_0
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.3=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.47.2=hee588c1_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.50.0=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nbconvert-core=7.16.6=py39h06a4308_0
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=py39h06a4308_0
  - nodejs=22.13.0=hf235a45_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openssl=3.4.1=h7b32b05_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=py39h06a4308_0
  - parso=0.8.4=py39h06a4308_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt_toolkit=3.0.50=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=26.2.0=py39h6a678d5_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=py39h06a4308_1
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - rpds-py=0.22.3=py39h4aa5aa6_0
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tinycss2=1.4.0=py39h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py39h5eee18b_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing-extensions=4.12.2=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - websocket-client=1.8.0=py39h06a4308_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.13=py39h06a4308_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - affine==2.4.0
    - alabaster==0.7.16
    - albucore==0.0.20
    - albumentations==1.4.21
    - annotated-types==0.7.0
    - anyio==4.7.0
    - arrow==1.3.0
    - asciitree==0.3.3
    - astunparse==1.6.3
    - attrs==24.2.0
    - babel==2.16.0
    - beautifulsoup4==4.12.3
    - blinker==1.9.0
    - bokeh==3.4.3
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cloudpickle==3.1.0
    - configargparse==1.7
    - contourpy==1.3.0
    - cycler==0.12.1
    - cythonpackage==0.2.14
    - dash==2.18.2
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - debugpy==1.8.10
    - decorator==5.1.1
    - deeperhistreg==1.0.1
    - dicomweb-client==0.59.3
    - distinctipy==1.3.4
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - docutils==0.21.2
    - docx2txt==0.8
    - eval-type-backport==0.2.2
    - fasteners==0.19
    - filelock==3.16.1
    - flask==3.0.3
    - flask-cors==5.0.0
    - flatbuffers==24.3.25
    - fonttools==4.55.3
    - fqdn==1.5.1
    - fsspec==2024.10.0
    - gast==0.6.0
    - gdown==5.2.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - glymur==0.13.6
    - google-pasta==0.2.0
    - grpcio==1.68.1
    - h5py==3.12.1
    - huggingface-hub==0.26.5
    - imagecodecs==2024.9.22
    - imageio==2.37.0
    - imagesize==1.4.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipympl==0.9.7
    - ipython==8.18.1
    - ipython-genutils==0.2.0
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - jsonpointer==3.0.0
    - jupyter-contrib-core==0.4.2
    - jupyter-contrib-nbextensions==0.7.0
    - jupyter-events==0.10.0
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-nbextensions-configurator==0.6.4
    - jupyter-server==2.14.2
    - jupyterlab==4.3.2
    - keras==3.7.0
    - kiwisolver==1.4.7
    - kwarray==0.7.1
    - kwimage==0.11.2
    - lazy-loader==0.4
    - libclang==18.1.1
    - llvmlite==0.43.0
    - lpips==0.1.4
    - lxml==5.3.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - marshmallow==3.26.1
    - matplotlib==3.9.3
    - mdurl==0.1.2
    - mistune==3.0.2
    - ml-dtypes==0.4.1
    - monai==1.4.0
    - mpmath==1.3.0
    - namex==0.0.8
    - nbclient==0.10.1
    - nbconvert==7.16.4
    - networkx==3.2.1
    - nntool==1.3.0
    - nodejs-bin==18.4.0a4
    - notebook==7.3.1
    - numba==0.60.0
    - numcodecs==0.12.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - open3d==0.19.0
    - opencv-contrib-python==4.11.0.86
    - opencv-python==4.9.0.80
    - opencv-python-headless==4.11.0.86
    - openslide-bin==4.0.0.6
    - openslide-python==1.4.1
    - opt-einsum==3.4.0
    - optree==0.13.1
    - pandas==2.2.3
    - pandocfilters==1.5.1
    - parse==1.20.2
    - pillow==11.0.0
    - plotly==5.24.1
    - prompt-toolkit==3.0.48
    - protobuf==5.29.1
    - psutil==6.1.0
    - pyarrow==19.0.1
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pydicom==2.4.4
    - pygments==2.18.0
    - pynndescent==0.5.13
    - pyparsing==3.2.0
    - pyquaternion==0.9.9
    - python-json-logger==2.0.7
    - pytorch-msssim==1.0.0
    - pytz==2024.2
    - pyvips==2.0.2
    - referencing==0.35.1
    - regex==2024.11.6
    - retrying==1.3.4
    - rich==13.9.4
    - safetensors==0.4.5
    - scikit-image==0.24.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - seaborn==0.13.2
    - send2trash==1.8.3
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - shapely==2.0.6
    - shtab==1.7.1
    - simpleitk==2.4.0
    - simsimd==6.2.1
    - smmap==5.0.2
    - snowballstemmer==3.0.1
    - soupsieve==2.6
    - sphinx==7.4.7
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - stringzilla==3.12.5
    - submitit==1.5.2
    - sympy==1.13.1
    - tenacity==9.0.0
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.18.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.5.0
    - terminado==0.18.1
    - tf-keras==2.18.0
    - threadpoolctl==3.5.0
    - tiatoolbox==1.6.0
    - tifffile==2024.8.30
    - timm==1.0.12
    - tokenizers==0.21.0
    - torch==2.5.1
    - torchvision==0.20.1
    - tqdm==4.67.1
    - transformers==4.51.0.dev0
    - triton==3.1.0
    - typeguard==4.4.1
    - types-python-dateutil==2.9.0.20241206
    - tyro==0.9.5
    - tzdata==2024.2
    - ubelt==1.3.7
    - ucimlrepo==0.0.7
    - umap-learn==0.5.7
    - universal-pathlib==0.2.6
    - uri-template==1.3.0
    - urllib3==2.2.3
    - wandb==0.19.1
    - webcolors==24.11.1
    - webencodings==0.5.1
    - werkzeug==3.0.6
    - wordcloud==1.9.4
    - wrapt==1.17.0
    - wsidicom==0.20.6
    - xyzservices==2025.4.0
    - zarr==2.18.2
    - zuko==1.3.0
prefix: /home/leiy28/.conda/envs/general_python2
